## 1 Error occured after 'jupyter notebook'

ssl.SSLError: [SSL: EE_KEY_TOO_SMALL] ee key too small (_ssl.c:4022)
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(5, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(5, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3/dist-packages/tornado/platform/asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "/usr/lib/python3/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/tornado/netutil.py", line 262, in accept_handler
    callback(connection, address)
  File "/usr/lib/python3/dist-packages/tornado/tcpserver.py", line 260, in _handle_connection
    connection = ssl_wrap_socket(connection,
  File "/usr/lib/python3/dist-packages/tornado/netutil.py", line 565, in ssl_wrap_socket
    context = ssl_options_to_context(ssl_options)
  File "/usr/lib/python3/dist-packages/tornado/netutil.py", line 540, in ssl_options_to_context
    context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
ssl.SSLError: [SSL: EE_KEY_TOO_SMALL] ee key too small (_ssl.c:4022)

Solution Reference: https://github.com/jupyter/notebook/issues/507
Run this
$sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout mycert.key -out mycert.pem
then run this
$sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout mycert.pem -out mycert.pem



## 2 Error occured when using ssh connects to the cloud VM

f@f-virtual-machine:~/Desktop$ ssh -i home/f/delabsshkey.pem ubuntu@130.238.29.121
Warning: Identity file home/f/delabsshkey.pem not accessible: No such file or directory.
The authenticity of host '130.238.29.121 (130.238.29.121)' can't be established.
ECDSA key fingerprint is SHA256:ZqUMz5JdM9C4yzuvpZZU2GAGp1RQWhdo5m0eH7ytC5w.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '130.238.29.121' (ECDSA) to the list of known hosts.
ubuntu@130.238.29.121: Permission denied (publickey).

Solution: Ref Link: https://askubuntu.com/questions/311558/ssh-permission-denied-publickey
chmod 700 .ssh
chmod 600 .ssh/authorized_keys
Also for No such file or directory ==> notice for inputting the path: /home/f/delabsshkey.pem 


